// import './globals.css'
import './home.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div>n1</div>
        {children}
        <div>end</div>
      </body>
      
    </html>
  )
}
